import "./globals.css";
import Header from "./header";
import Footer from "./footer";
export const metadata = {
  title: "Gods",
  description: "Generated by harshita",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
